extends: 'airbnb'

env:
  browser: true
  jest: true

globals:
  chrome: false

rules:
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true

  jsx-a11y/interactive-supports-focus:
    - off

  jsx-a11y/click-events-have-key-events:
    - off

  # ensure consistency when using newlines within a function’s parens
  function-paren-newline:
    - error
    - consistent

  # object keys must have at least one space after the colon
  key-spacing:
    - error
    - mode: 'minimum'

  # Allow index files in cyclical dependency tracking
  import/no-cycle:
    - error
    - maxDepth: 1

  lines-between-class-members:
    - off

  # allow console use
  no-console:
    - off

  # though we don’t enforce, only use multi spaces for alignment
  no-multi-spaces:
    - off

  # prevent unused expressions that have no effect on program state
  no-unused-expressions:
    - error
    - allowShortCircuit: true
      allowTernary: true

  # remove all unused variables
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_' # ignore vars with a _ prefix (e.g. _foo)

  # Place operators at the ends of lines when doing linebreaks
  operator-linebreak:
    - error
    - after

  # though we don’t enforce, prefer destructuring when it makes sense
  prefer-destructuring:
    - off

  # though we don’t enforce, prefer destructuring props only when its minimal; it’s better to be
  # explicit about where they’re coming from
  react/destructuring-assignment:
    - off

  # allow multiple expressions on the same line, e.g. `<App><Hello /> World</App>`
  react/jsx-one-expression-per-line:
    - off

  # allow defining props with a spread, e.g. <foo {...props} />
  react/jsx-props-no-spreading:
    - off

  react/sort-comp:
    - error
    - order:
      - static-variables
      - static-methods
      - lifecycle
      - everything-else
      - render

  react/static-property-placement:
    - error
    - static public field

  # never use semi-colons
  semi:
    - error
    - never

overrides:
  - files:
    - 'test/**/*.js'
    rules:
      max-classes-per-file: off

parser: 'babel-eslint'

settings:
  import/resolver:
    babel-module: {}

    # Use our webpack configuration for resolving modules
    webpack:
      config: 'webpack.config.js'
